export const Cars = [
  {
    id: "1",
    name: "Koenigsegg",
    type: "Sportscar",
    thumbnail: "/koenig.png",
    gallery: ["/koenig.png", "/View3.png", "/View2.png"],
    price: "100.00",
    seats: "2",
    spending: "100",
    description: "The Koenigsegg Agera is a high-performance sports car produced by the Swedish manufacturer Koenigsegg. It is known for its extreme speed and performance.",
  },
  {
    id: "2",
    name: "All new Rush",
    type: "SUV",
    thumbnail: "/new-rush.png",
    gallery: ["/new-rush.png", "/View3.png", "/View2.png"],
    price: "80.00",
    seats: "2",
    spending: "80",
    description: "The All new Rush is a high-performance sports car produced by the Swedish manufacturer All new Rush. It is known for its extreme speed and performance.",
  },
  {
    id: "3",
    name: "Nissan GTR-34",
    type: "Sports Car",
    thumbnail: "/nissan-gtr.png",
    gallery: ["/nissan-gtr-view1.png", "/View3.png", "/View2.png"],
    price: "80.00",
    seats: "2",
    spending: "80",
    description: "The Nissan GTR-34 is a high-performance sports car produced by the Japanese manufacturer Nissan. It is known for its extreme speed and performance.",
  },
  {
    id: "4",
    name: "Rolls-Royce",
    type: "Luxury Car",
    thumbnail: "/rolls-royce.png",
    gallery: ["/rolls-royce.png", "/View3.png", "/View2.png"],
    price: "90.00",
    seats: "2",
    spending: "90",
    description: "The Rolls-Royce is a high-performance sports car produced by the British manufacturer Rolls-Royce. It is known for its extreme speed and performance.",
  },
  {
    id: "5",
    name: "CR-V",
    type: "SUV",
    thumbnail: "/cr-v.png",
    gallery: ["/cr-v.png", "/View3.png", "/View2.png"],
    price: "80.00",
    seats: "2",
    spending: "80",
    description: "The CR-V is a high-performance sports car produced by the Japanese manufacturer Honda. It is known for its extreme speed and performance.",
  }, {
    id: "6",
    name: "All new Rush",
    type: "SUV",
    thumbnail: "/new-rush.png",
    gallery: ["/new-rush.png", "/View3.png", "/View2.png"],
    price: "90.00",
    seats: "2",
    spending: "80",
    description: "The All new Rush is a high-performance sports car produced by the Swedish manufacturer All new Rush. It is known for its extreme speed and performance.",
  },
  {
    id: "7",
    name: "Nissan GTR-34",
    type: "Sports Car",
    thumbnail: "/nissan-gtr.png",
    gallery: ["/nissan-gtr.png", "/View3.png", "/View2.png"],
    price: "90.00",
    seats: "2",
    spending: "80",
    description: "The Nissan GTR-34 is a high-performance sports car produced by the Japanese manufacturer Nissan. It is known for its extreme speed and performance.",
  },
  {
    id: "8",
    name: "Rolls-Royce",
    type: "Luxury Car",
    thumbnail: "/rolls-royce.png",
    gallery: ["/rolls-royce.png", "/View3.png", "/View2.png"],
    price: "90.00",
    seats: "2",
    spending: "90",
    description: "The Rolls-Royce is a high-performance sports car produced by the British manufacturer Rolls-Royce. It is known for its extreme speed and performance.",
  }, {
    id: "9",
    name: "Koenigsegg",
    type: "Sportscar",
    thumbnail: "/koenig.png",
    gallery: ["/koenig.png", "/View3.png", "/View2.png"],
    price: "100.00",
    seats: "2",
    spending: "100",
    description: "The Koenigsegg Agera is a high-performance sports car produced by the Swedish manufacturer Koenigsegg. It is known for its extreme speed and performance.",
  },
  {
    id: "10",
    name: "All new Rush",
    type: "SUV",
    thumbnail: "/new-rush.png",
    gallery: ["/new-rush.png", "/View3.png", "/View2.png"],
    price: "80.00",
    seats: "2",
    spending: "80",
    description: "The All new Rush is a high-performance sports car produced by the Swedish manufacturer All new Rush. It is known for its extreme speed and performance.",
  },
  {
    id: "11",
    name: "Nissan GTR-34",
    type: "Sports Car",
    thumbnail: "/nissan-gtr.png",
    gallery: ["/nissan-gtr.png", "/View3.png", "/View2.png"],
    price: "80.00",
    seats: "2",
    spending: "80",
    description: "The Nissan GTR-34 is a high-performance sports car produced by the Japanese manufacturer Nissan. It is known for its extreme speed and performance.",
  }, {
    id: "12",
    name: "All new Rush",
    type: "SUV",
    thumbnail: "/new-rush.png",
    gallery: ["/new-rush.png", "/View3.png", "/View2.png"],
    price: "80.00",
    seats: "2",
    spending: "80",
    description: "The All new Rush is a high-performance sports car produced by the Swedish manufacturer All new Rush. It is known for its extreme speed and performance.",
  },
]