export const Cars = [
  {
    id: 1,
name: "Koenigsegg",
type: "Sportscar",
image: "/koenig.png",
price: "100.00",
seats: "2",
spending: "100",
  },
  {
    id: 2,
    name: "All new Rush",
    type: "SUV",
    image: "/new-rush.png",
    price: "80.00",
    seats: "2",
    spending: "80",
},
{
  id: 3,
  name: "Nissan GTR-34",
    type: "Sports Car",
    image: "/nissan-gtr.png",
    price: "80.00",
    seats: "2",
    spending: "80",
},
{
  id: 4,
  name: "Rolls-Royce",
    type: "Luxury Car",
    image: "/rolls-royce.png",
    price: "90.00",
    seats: "2",
    spending: "90",
},
{
  id: 5,
  name: "CR-V",
    type: "SUV",
    image: "/cr-v.png",
    price: "80.00",
    seats: "2",
    spending: "80",
},{
  id: 6,
  name: "All new Rush",
  type: "SUV",
  image: "/new-rush.png",
  price: "90.00",
  seats: "2",
  spending: "80",
},
{
  id: 7,
name: "Nissan GTR-34",
  type: "Sports Car",
  image: "/nissan-gtr.png",
  price: "90.00",
  seats: "2",
  spending: "80",
},
{
  id: 8,
 name: "Rolls-Royce",
  type: "Luxury Car",
  image: "/rolls-royce.png",
  price: "90.00",
  seats: "2",
  spending: "90",
},{
  id: 9,
  name: "Koenigsegg",
  type: "Sportscar",
  image: "/koenig.png",
  price: "100.00",
  seats: "2",
  spending: "100",
    },
    {
      id: 10,
      name: "All new Rush",
      type: "SUV",
      image: "/new-rush.png",
      price: "80.00",
      seats: "2",
      spending: "80",
  },
  {
    id: 11,
    name: "Nissan GTR-34",
    type: "Sports Car",
    image: "/nissan-gtr.png",
    price: "80.00",
    seats: "2",
    spending: "80",
  },
]