export const Reviews = [
  {
    id: 1,
    name: "John Doe",
    rating: 5,
    comment: "This is a great product! Amazing service! I would recommend it to my friends. As Manager i think you should improve your service.",
    date: "2025-01-01",
    position: "Manager at Google",
  },
  {
    id: 2,
    name: "Jane Doe",
    rating: 4,
    comment: "This is a great product! Good service! I would recommend it to my friends. As CEO i think you should improve your service.",
    date: "2025-01-01",
    position: "CEO at Delta",
  },
  {
    id: 3,
    name: "Jim Doe",
    rating: 3,
    comment: "This is a great product and average service! but the price is a bit high. I would recommend it to my friends. As CTO i think you should improve your service.",
    date: "2025-01-01",
    position: "CTO at Google",
  },
  {
    id: 4,
    name: "Jill Doe",
    rating: 2,
    comment: "This is a great product! Bad service! I would not recommend it to my friends. As Engineer i think you should improve your service.",
    date: "2025-01-01",
    position: "Engineer at Apple",
  },
  {
    id: 5,
    name: "Jack Doe",
    rating: 1,
    comment: "This is a great product! Terrible service! I would not recommend it to my friends. As Manager i think you should improve your service.",
    date: "2025-01-01",
    position: "Manager at Microsoft",
  },
  {
    id: 6,
    name: "Michael Jordan",
    rating: 2,
    comment: "This is a great product! Bad service! I would recommend it to my friends. As CEO i think you should improve your service.",
    date: "2025-01-01",
    position: "CEO at Amazon",
  },
];